### ISSUE TITLE
add AppBundle skeleton code

### ISSUE THREAD

**Issue by anacona16** [CawaKharkov/symfony-micro#4]
What do you think about add the AppBundle skeleton code? The main idea is add a controller class in where set the router with annotations and mount it, like this:

``` php
$routes->mount('/', $routes->import('@AppBundle/Controller', 'annotation'));
```

Having the actions in the MicroKernel class is a good solution for one action, but when you have 5 actions or more for example, isn't a good solution.

**Comment by cawa87** [comment]
Good idea, but I suggest not to use `\Symfony\Bundle\FrameworkBundle\Controller\Controller`
to improve speed.

**Comment by anacona16** [comment]
How would you do it? How would you access to templating service?

**Comment by cawa87** [comment]
I've checked `\Symfony\Bundle\FrameworkBundle\Controller\Controller`
it have not much dependencies, so we can just use it, and don't invent  the bicycle.

**Comment by anacona16** [comment]
See #6
