### ISSUE TITLE
Does the index page because no outside MicroKernel.php?

### ISSUE THREAD

**Issue by chiqui3d** [CawaKharkov/symfony-micro#7]
It could create a bundle of home page and not have to touch the microkernel to set the home page?

**Comment by cawa87** [comment]
There's an AppBundle with [DefaultController](https://github.com/CawaKharkov/symfony-micro/blob/master/src/AppBundle/Controller/DefaultController.php).

**Comment by chiqui3d** [comment]
Ahh, Sorry I did not see it, now is perfect.
